### ISSUE TITLE
Investigate occasional NPE in Handler Adapter

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-community/memcache-release#9]
I've seen an occasional NPE on the servers.  Most likely caused by a memcache client nuance.  The annoying thing is the root cause exception doesn't get logged for some reason I don't understand.  I need to fix logging so the entire stack trace is logged and then fix the NPE.

Here is the exception I see:

```
2016-04-22T16:50:42.580+0000 [ERROR] c.m.MemcacheInboundHandlerAdapter: Error while invoking MemcacheMsgHandler
java.lang.ArrayIndexOutOfBoundsException: null
java.lang.NullPointerException
 at cloudfoundry.memcache.MemcacheUtils.lambda$returnFailure$24(MemcacheUtils.java:26)
 at cloudfoundry.memcache.MemcacheUtils$$Lambda$17/91043545.send(Unknown Source)
 at cloudfoundry.memcache.MemcacheInboundHandlerAdapter.channelRead(MemcacheInboundHandlerAdapter.java:192)
 at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
 at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
 at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
 at cloudfoundry.memcache.MemcacheOrderingDuplexHandler.channelRead(MemcacheOrderingDuplexHandler.java:30)
 at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
 at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
 at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
 at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:947)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
 at java.lang.Thread.run(Thread.java:745)
```

**Comment by youngm** [comment]
Reworked a lot fo this code.  Hopefully this goes away.
